[package]

name = "miniz-sys"
version = "0.2.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
links = "miniz"
build = "build.rs"
license = "(MIT OR Apache-2.0) AND Unlicense"
repository = "https://github.com/alexcrichton/flate2-rs"
documentation = "https://docs.rs/miniz-sys"
description = """
Bindings to the miniz.c library.
"""
categories = ["external-ffi-bindings"]

[lib]
name = "miniz_sys"
path = "lib.rs"

[build-dependencies]
gcc = "0.3"
